name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install dbt-bigquery==1.7.0 google-cloud-bigquery==3.11.4 google-cloud-bigquery-storage==2.22.0

      - name: Create GCP credentials file
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" > /tmp/gcp_key.json
          cat /tmp/gcp_key.json | python3 -c "import sys,json; json.load(sys.stdin); print('Valid JSON!')"

      - name: Run dbt compile
        working-directory: transform/gas_prices
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_key.json
        run: |
          dbt compile --profiles-dir /home/runner/work/gas-price-pipeline/gas-price-pipeline/transform/gas_prices

      - name: Run dbt test
        working-directory: transform/gas_prices
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_key.json
        run: |
          dbt test --profiles-dir /home/runner/work/gas-price-pipeline/gas-price-pipeline/transform/gas_prices
